# -*- encoding : utf-8 -*-

#
# GLOBAL WAT DEFAULTS
#

default_preview_length: 300 # Chracters
image_magick_path: "/usr/local/bin"
max_twitter_messages: 3

application_name: "W.A.T."
start_search_at_min_chars: 3

timeline:
  reload_interval: 5
  default_duration: 120
  event_classes:
    timeline_event:
      threshold: 10
    user_message:
      threshold: 10
    doorkeeper_event:
      threshold: 900
    comment_event:
      threshold: 300
    page_event:
      threshold: 300