# Test Settings
smtp_server: mail.example.com
smtp_port: 25
smtp_domain: example.com
smtp_user: username
smtp_password: 'secret'
smtp_authentication: plain
smtp_enable_starttls_auto: true
smtp_host: "www.example.com"
smtp_default_from: "noreply@example.com"

application_brand: "WAT-HOME"
application_mail_signature: WAT TEST APPLICATION
application_mail_subject_prefix: "WAT: "

supress_page_title: false
multilanguage: true

api:
  tokens:
    - "API_TEST_TOKEN"

timeline:
  reload_interval: 5
  default_duration: 1440